### ISSUE TITLE
Problem load fbx model with DigitalRune

### ISSUE THREAD

**Issue by polyminthe** [DigitalRune/DigitalRune#5]
Hi guys, i have a problem when i try to load a fbx model with DigitalRune. It's little bit weird cause before with the trial version, everything goes well. 
Here is the message i get on the Monogame pipeline tools : 
**'System.Object DigitalRune.Animation.Character.Skeleton.get_Internals()'**

If somebody know how to solve this problem, i will be very gratefulto him ^^
Many thanks in advance, i keep hope

**Comment by luxbinary** [comment]
Hi polyminthe,
I think there shouldn`t be any differences between the trial and the open source version of the content pipeline.
Only thing  I can recommend you is to use the release version, not the debug version.
You can also start the pipeline tool in debug mode. Menu->Build->DebugMode.
Than you can debug the pipeline inside Visual Studio and hopefully get better exception infos.

**Comment by polyminthe** [comment]
Thank you @Lu05  , you advice me nice. I just change the target dll to release and now it's working perfectly
