### ISSUE TITLE
What kind of (Import) and (CPU) to use for loading models (FBX) on Universall App?

### ISSUE THREAD

**Issue by polyminthe** [DigitalRune/DigitalRune#6]
Hi, I'm coming here cause i meet some problem for loading the models in my project. I don't know wich configuration i need use for build my Fbx models for Universal App.
Here i find the official documentation, but only for build the Fbx models for Windows desktop App.

http://digitalrune.github.io/DigitalRune-Documentation/html/53ee55e3-b4a5-42cc-b47d-88d18b9de2f5.htm

Why about universal app please ?

**Comment by luxbinary** [comment]
The linked documentation is for **XNA**-Games. Universal Windows Apps are only available for Monogame builds.
There you should use the pipeline tool to build your content(Source\MonoGame\Tools\Pipeline\bin\Windows\AnyCPU\Release\Pipeline.exe) like in the samples.
For the content the cpu doesn't matter. As importer you should use the Monogame FBX importer.
The big difference between Windows-Desktop/Universal and Windows-Phone/Store is the graphics profile. First one is HiDef, second is Reach.
Have a look at the headers of the *.mgcb-files at Samples\Content\
Use this as an example to make your own mgcb-file for the content pipeline.

**Comment by polyminthe** [comment]
Thank you @Lu05  you have perfectly answered my question  :-) Have a nice day
